# Demo Cluster Kubeconfig
# 
# This is the kubeconfig for our public demo cluster running the OTEL demo app.
# Safe to commit - authentication requires AWS IAM credentials (not included here).
# The cluster is used to demonstrate IncidentFox investigating and fixing injected failures.
#
# To use: export AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... AWS_REGION=us-west-2

apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTUxUci9zd3NGMjB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1qa3dORFF5TXpKYUZ3MHpOVEV4TWpjd05EUTNNekphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURaVDJiK29RU0V0RWd6QUFQTkN0cnFGc0tUd3paWTk4cUxGT2NxdXNMdGZ1SXp2bnl0UUUrMnErK1cKVHBsb3JYWXdRb1lJM2lUTkxCUFJkdjZxSG91Q0hTekZGMGIwOGd6RnQyeHBqTGdtMUlmNGRPWDl3c1VSVE1PRgpiYjZPT0daZm5HdU5ER3hNT0R5cEZmTW56NnRCSTRwaVAxNmFySllJMEErbUMzcGVrQVYzMCs0YmZsZ1dHem1FCldYeGI4SWtqeUtpSjNYT0gySGNHZVg4eVNwZkhVYzA1WEd0RUxEYmxWbVJxejlwSkJVNHlndXZYVnBmZk1ZQzYKMGVFdzloaHhqL1ZPOEhxbGtzcDg4SThYNVZLT1p0THR0WVVKVkJHelZ6QmgwWWdYUmNMMk1aMlV4TFFDZ3R1aQprcXhpYTVWOXJ0ZEExSUZ6dURkVHd2QkhWZTlSQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUT0RpMTRLVnk1b2toYlBoRTR1MU9KamN3c1ZUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3Z6ZlQxdjZKSAo3bGhPOURJckNqTzVaYmdVRDFiTFQvRFBBL3JRb2drSlJvQTRZVUZpN25FaFpMNU9JZVREem81Yk05VE1DVzAyClUvejZ6L0dWTC9LZ2pWMjZQZDNTbHlCcHpab2ZVODVaRC95WTVZK0lTTlk2T0Y4QzhDa0dYKzhYR3Zlc3hCcHEKeHk0REk4RHduT0VZcWFObmFrT0ZWZmNDY1NiSm92VkZFb3VnK1hSWDZCcGpVZm55OFF4dlFrTzRxWC9PdXdRYwp0dnV4aVM2OVhuT1loYmdocjF4QWFpcy85UEpEUVB2NzZuMzkzUGRYckpGQjlrRjJ6V2dIek8zOElaWDFYZkJqCjJEdzMrUm1nNjFmQTcwOTlhUW5Bd1BHQVp3MWtlNFhDNktiZTZiblI0V2UvQ1lmdWlFVWc4Yk5hTkVHWlpwZFcKT1dmTWs0SDNWNjdvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://304AD82503B86D2F95FE7E433719BABC.gr7.us-west-2.eks.amazonaws.com
  name: incidentfox-demo
contexts:
- context:
    cluster: incidentfox-demo
    user: incidentfox-demo
  name: incidentfox-demo
current-context: incidentfox-demo
users:
- name: incidentfox-demo
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - incidentfox-demo
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
